version: '3'
services:

   dcbot:
     container_name: Discord_Bot
     image: dc-bot-python:latest
     network_mode: "host"
     restart: unless-stopped
     volumes:
       - /portainer/Files/AppData/Config/DiscordBot/config:/app/utils